try5

diff --git a/.github/workflows/buildAMI.yml b/.github/workflows/buildAMI.yml
--- a/.github/workflows/buildAMI.yml
+++ b/.github/workflows/buildAMI.yml
@@ -116,7 +116,26 @@ jobs:
             --launch-template LaunchTemplateName=CSYE6225_lauch_temp,Version='$Latest'
     - name: Refresh Instance
       run: |
-        aws autoscaling start-instance-refresh --auto-scaling-group-name CSYE6225_auto_scaling
+        refresh_id = $(aws autoscaling start-instance-refresh \
+            --auto-scaling-group-name CSYE6225_auto_scaling \
+            --query 'InstanceRefreshId' --output text)
+        echo "REFRESH_ID=$refresh_id" >> $GITHUB_ENV
+
+    - name: Wait for Instance Refresh Completion
+      run: |
+        while true; do
+          status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name CSYE6225_auto_scaling --instance-refresh-ids ${{env.REFRESH_ID}} --query 'InstanceRefreshes[0].Status' --output text)
+          echo "Current status: $status"
+          if [[ $status == "Successful" ]]; then
+            echo "Instance refresh completed successfully."
+            exit 0
+          elif [[ $status == "Failed" || $status == "Cancelled" ]]; then
+            echo "Instance refresh failed."
+            exit 1
+          fi
+          sleep 60
+        done
+    
 
 
   
